name: MVMFrontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: ng build --configuration=production

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: mvm.techwagger.com           # Replace with your server's host
          username: YOUR_USERNAME            # Replace with your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key stored in GitHub Secrets
          source: dist/                      # Folder to deploy
          target: /var/www/web               # Target folder on your server
